const data = {
  products: [
    {
      name: "Nike Slim shirt",
      id: "nike-slim-shirt",
      catagory: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Adidas Slim pant",
      id: "Adidas-slim-pant",
      catagory: "Pant",
      image: "/images/p2.jpg",
      price: 220,
      countInStock: 11,
      brand: "Adidas",
      rating: 4.8,
      numReviews: 12,
      description: "high quality pant",
    },
    {
      name: "Nike Slim shirt",
      id: "nike-slim-shirt1",
      catagory: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 13,
      brand: "Nike",
      rating: 4.5,
      numReviews: 13,
      description: "high quality shirt",
    },
    {
      name: "Adidas Slim pant",
      id: "Adidas-slim-pant1",
      catagory: "Pant",
      image: "/images/p2.jpg",
      price: 220,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.8,
      numReviews: 15,
      description: "high quality pant",
    },
  ],
};

module.exports = data;
